version: '3.8'

services:
  dashboard-pi:
    build: .
    container_name: dashboard-pi
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      # Permitir controlar el demonio Docker del host
      - /var/run/docker.sock:/var/run/docker.sock
      # Permitir lectura de métricas reales del hardware del host Raspberry Pi
      - /proc:/proc:ro
      - /sys:/sys:ro
      # Carpeta donde se clonarán y desplegarán las apps en el host (ajustar si es necesario)
      - ./apps:/root/apps
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - red-publica

networks:
  # Le indicamos a Docker que esta red ya fue creada manualmente y no debe intentar crearla de nuevo
  red-publica:
    external: true